# Generated by Django 3.2.6 on 2021-09-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piplup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='text',
            field=models.CharField(default='text', max_length=100),
            preserve_default=False,
        ),
    ]
