# Generated by Django 3.2.6 on 2021-09-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piplup', '0002_wallpaper_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallPaper2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
    ]
