# Generated by Django 3.2.6 on 2021-09-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piplup', '0003_wallpaper2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WallPaper2',
        ),
    ]
